config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get '_list' => 'books#_list'
  get 'home/about' => 'homes#about'
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :body, length: { maximum: 200}

	validates :title, presence: true

	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:name]
  attachment :profile_image

  has_many :books



  validates :name,
  length: { minimum: 2, maximum: 20}

  validates :introduction,
  length:{ maximum: 50}

  validates_uniqueness_of :name
  validates_presence_of :name



  #登録時にemailを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	# ログイン後に遷移するページ
  def after_sign_in_path_for(resource)
  		flash[:notice] = "signed in successfully."
     	user_path(current_user.id)
  end
  	#ログアウト後に遷移するページ
  def after_sign_out_path_for(resource)
        flash[:alert] = "signed out successfully."
        root_path
  end

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up,keys:[:email])

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	def index
		@book = Book.new
		@books = Book.all
		@user = current_user
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "book was successfully created"
			redirect_to book_path(@book)
		else
			@books = Book.all
			@user = current_user
			render :index
		end
	end

	def show
		@book = Book.find(params[:id])
		@user = @book.user
		@books = Book.new
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user != current_user
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
	    if @book.update(book_params)
	    	flash[:notice] = "You have updated book successfully."
	    	redirect_to book_path(@book)
	    else
	    	render :edit
	    end
	end

	def destroy
	    @book = Book.find(params[:id])
	    @book.destroy
	    redirect_to books_path
	end
	private

	def book_params
		params.require(:book).permit(:title, :body, :edit, :update, :destroy)
	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
		
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
		@users = User.all
		@user = current_user
		@book = Book.new
	end

	def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = @user.books
	end

	def edit
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to user_path(current_user)
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "You have updated user successfully."
			redirect_to user_path(@user.id)
		else
			render :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_books_helper.rb
module PostBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<section class="user-info">
	<h2 class=user-info-title>User info</h2>
	<%= attachment_image_tag user, :profile_image, size:"150x150", fallback:"bird-free.jpg"  %>
	<table class="table">
		<tr>
			<th>name</th>
			<td><%= @user.name %></td>
		</tr>
		<tr>
			<th>introduction</th>
			<td><%= @user.introduction %></td>
		</tr>
	</table>
	<%= link_to "", edit_user_path(user), class: "btn btn-default btn-block glyphicon glyphicon-wrench" %>
</section>

<section class="new-book">
	<h2 class="new-book-title">New book</h2>
	<%= form_for(Book.new) do |f| %>
		<h3>Title</h3>
		<%= f.text_field :title %>
		<h3>Opinion</h3>
		<%= f.text_area :body%>
		<%= f.submit 'Create Book'%>
	<% end %>
</section>

app/views/books/edit.html.erb
<section>

<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <p class="error-message"><%= @book.errors.count %>error occurred</p>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@book) do |f| %>
	<h3>Title</h3>
	<%= f.text_field :title %>
	<h3>Opinion</h3>
	<%= f.text_area :body%>
	<%= f.submit 'Update Book' %>
<% end %>

<%= link_to "show", edit_book_path(@book)%>
<%= link_to "back", books_path(@book)%>
</section>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <p class="error-message"><%= @book.errors.count %>error occurred</p>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'books/list', book: @book , user: @user %>
		</div>
		<div class="col-lg-9">
			<table class="table">
				<caption>Books</caption>
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
							<th><%= attachment_image_tag book.user, :profile_image, size:"30x30", fallback:"bird-free.jpg" %></th>
							<td><%= link_to book.title, book_path(book.id) %></td>
							<td><%= book.body %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'books/list', book: @books, user: @book.user %>
		</div>
		<div class="col-lg-9">
			<table class="table">
				<caption>Book detail</caption>
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th><%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag @book.user, :profile_image, size:"100x100", fallback:"bird-free.jpg" %>
							<br><%= @user.name %>
							<% end %>
						</th>
						<td><%= link_to @book.title, book_path(@user) %></td>
						<td><%= @book.body %></td>
					</tr>
				</tbody>
			</table>
			<% if @book.user == current_user %>
				<%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
				<%= link_to "Destroy", book_path(@book), class: "btn btn-danger", method: :delete %>
			<% end %>
		</div>
	</div>
</div>

app/views/homes/about.html.erb
<section>
	<div class="top-container">
		<h1 class="top-header">Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
	</div>
</section>

app/views/homes/top.html.erb
<% if flash[:alert] %>
  <p><%= flash[:alert] %></p>
<% end %>

<section>
	<div class="top-container">
		<h1 class="top-header">Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
		<p class="top-text">In <span class="glyphicon glyphicon-book" aria-hidden="true">Bookers,</span><br>
			you can share and exchange your opinions , impressions , and emotions <br>
			about varioius books!
		</p>
		<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info btn-lg btn-block" %>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-success btn-lg btn-block" %>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <p class="navbar-brand"> Bookers</p>
    </div>

    <div class="collapse navbar-collapse" id="navbarEexample">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%=link_to "Home", user_path(current_user.id) %></li>
          <li><%=link_to "Users", users_path %></li>
          <li><%=link_to "Books", books_path %></li>
          <li><%=link_to "logout", destroy_user_session_path, method: :delete %></li>
        </ul>

      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%=link_to "Home","/" %></li>
          <li><%=link_to "About","/home/about" %></li>
          <li><%=link_to "login", new_user_session_path %></li>
          <li><%=link_to "sign up", new_user_registration_path %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>
</header>
    <%= yield %>
<footer>
  CopyRight Infratop.inc
</footer>


  </body>
</html>

app/views/users/edit.html.erb
<section class="edit-container">
	<% if @user.errors.any? %>
	  <p class="error-message">error occurred</p>
	  <div id="error_explanation" class="alert alert-danger">
	    <ul>
	      <% @user.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	    </ul>
	  </div>
	<% end %>
	<h1 class="user-info-title">User info</h1>
	<%= form_for(@user) do |f| %>
		<p class="edit-name">name</p>
		<%= f.text_field :name %>
		<p class="edit-image">Image</p>
		<%= f.attachment_field :profile_image %>
		<p class="edit-introduction">Introduction</p>
		<%= f.text_area :introduction %>
		<%= f.submit 'Update User'%>
	<% end %>
</section>

app/views/users/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'books/list', book:@book, user:@user%>
		</div>
		<div class="col-lg-9">
			<table class="table">
				<caption>Users</caption>
				<thead>
					<tr>
						<th>Image</th>
						<th>Name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<th><%= attachment_image_tag user, :profile_image, size:"30x30", fallback:"bird-free.jpg" %></th>
						<td><%= user.name %></td>
						<td><%= link_to "show", user_path(user) %></td>
					<% end %>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'books/list', book:@book, user:@user%>
		</div>
		<div class="col-lg-9">
			<table class="table">
				<caption>Books</caption>
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
						<th><%= attachment_image_tag book.user, :profile_image, size:"30x30" , fallback:"bird-free.jpg" %></th>
						<td><%= link_to book.title, book_path(book.id) %></td>
						<td><%= book.body %></td>
					<% end %>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>